### ISSUE TITLE
Frappe v14 - cannot import 'get_desk_sidebar_items'

### ISSUE THREAD

**Issue by Tom-Finke** [pstuhlmueller/workspaceperms#2]
I tried installing the app, but when I try to access the Bench i get an error message:

`cannot import name 'get_desk_sidebar_items' from 'frappe.desk.desktop' (/workspace/development/frappe-bench/apps/frappe/frappe/desk/desktop.py)`

Im on Frappe v14 and the Function get_desk_sidebar_items seems to have been renamed to get_workspace_sidebar_items
It was still there in v13: https://github.com/frappe/frappe/blob/version-13/frappe/desk/desktop.py#L377
And then in v14: https://github.com/frappe/frappe/blob/version-14-beta/frappe/desk/desktop.py#L337

I had to install the app and remove the 2 new lines from boot.py manually

```
from workspaceperms.utils.overrides import load_desktop_data_v2
load_desktop_data = load_desktop_data_v2
```

**Comment by pstuhlmueller** [comment]
Hi @Tom-Finke ,
as defined within "Requirements" this app is only compatible to v13.

In v13 there is a core-implementation that covers similar functionality, therefore there is no need to install this app on a v14 site.
