### ISSUE TITLE
Does not allow more than one workspace per role?

### ISSUE THREAD

**Issue by DrZoidberg09** [pstuhlmueller/workspaceperms#3]
Hi there,

if I want add another workspace and want to assign the roles, it says: Role Link (ROLE) does already exist.

Do I use it wrong or is it a bug?

**Comment by pstuhlmueller** [comment]
Has been fixed as part of https://github.com/pstuhlmueller/workspaceperms/commit/4a85138c15791ae6f8604d92376da50445cf67b0
