### ISSUE TITLE
sudo supervisorctl restart frappe:' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by bonface221** [pstuhlmueller/workspaceperms#4]
On bench restart. I'm getting this error.

sudo supervisorctl restart frappe:
frappe: ERROR (no such group)
frappe: ERROR (no such group)
ERROR: 
subprocess.CalledProcessError: Command 'sudo supervisorctl restart frappe:' returned non-zero exit status 2.

**Comment by pstuhlmueller** [comment]
@bonface221 , can you provide more information about the apps installed and its versions, please?

**Comment by bonface221** [comment]
after running `bench execute workspaceperms.seeds.execute` , the final step is to run bench restart which causes that error

**Comment by pstuhlmueller** [comment]
What version of frappe and erpnext do you use?

**Comment by bonface221** [comment]
erpnext 14.x.x-develop
frappe 15.x.x-develop
whitelabel 0.0.1

**Comment by pstuhlmueller** [comment]
As mentioned in the dependencies section, this app is only compatible with frappe v13.

In general, there is no relevance for this app from v14 upwards any longer, as "Workspaces 2.0" covers all (and more!) functionalities of this app.
