### ISSUE TITLE
After installation Internal Server Error

### ISSUE THREAD

**Issue by SureshParvathareddy** [pstuhlmueller/workspaceperms#5]
Hi After installing Internal server error occurred. Now I am not able access any of my sites. Please suggest how to troubleshoot

**Comment by pstuhlmueller** [comment]
Hi @SureshParvathareddy ,
please provide more information - what Frappe and ERPNext version do you have? What did you try so far?

**Comment by harshvadhiya** [comment]
Hi I'm facing the same issue..

{
	"erpnext": "14.63.3",
	"frappe": "14.66.2",
	"hrms": "14.22.0"
}

**Comment by harshvadhiya** [comment]
@SureshParvathareddy 

have you solved it??

**Comment by pstuhlmueller** [comment]
Hi @harshvadhiya ,
you have provided already the answer :-) The description says, this app is requiring **v13**. You are using v14, that's the reason why.

From v14 onwards there is also no reason why to use this app, as the feature is incorporated in standard functionality.

**Comment by harshvadhiya** [comment]
> Hi @harshvadhiya , you have provided already the answer :-) The description says, this app is requiring **v13**. You are using v14, that's the reason why.
> 
> From v14 onwards there is also no reason why to use this app, as the feature is incorporated in standard functionality.

oh, ok.
But now what can I do to remove the app?
this is not letting me in

I have tried `bench remove-from-installed-app workspaceperms` but no use. it didn't worked
